### ISSUE TITLE
share

### ISSUE THREAD

**Issue by jburel** [ome/omero-guides#80]
Shares have been deprecated but not really replaced by anything in the web client
It has been mentioned several times during workshops or discussion on forum see for example https://forum.image.sc/t/omero-sharing-data-with-users-you-are-not-in-a-group-with/48520/3

The closest we have is the "omero-cli-duplicate" plugin. An entry in the guide will be useful to have
cc @joshmoore @pwalczysko

**Comment by pwalczysko** [comment]
suggested fix in https://github.com/ome/omero-guide-introduction/pull/19

**Comment by pwalczysko** [comment]
Part of the problem here is that https://downloads.openmicroscopy.org/help/pdfs/sharing-data.pdf does not specify that the Shares are deprecating. As users still manage to find these pdf files, I think it would make sense to add the warning retrospectively ?

See discussion on https://github.com/ome/omero-guide-introduction/pull/19#issuecomment-785856392 though. The things are too much in flux at the moment.

**Comment by pwalczysko** [comment]
Fiixed by https://github.com/ome/omero-guide-introduction/pull/19 and also https://github.com/ome/omero-web/pull/265 and https://github.com/ome/www.openmicroscopy.org/pull/447
